{"posts":[{"tags":[{"name":"forums"},{"name":"lectures"},{"name":"week 7"},{"name":"tue 3-4 lecture video: fork(), _exit(), atexit(), wait()"},{"name":"atexit","salience":0.26776427030563354},{"name":"example","salience":0.2206876277923584},{"name":"function call","salience":0.1162082776427269},{"name":"jas","salience":0.11522240936756134},{"name":"function printing","salience":0.08993637561798096},{"name":"block","salience":0.07230931520462036},{"name":"main","salience":0.05733886733651161},{"name":"atexit","salience":0.024519069120287895},{"name":"thanks","salience":0.01474837027490139},{"name":"atexit function","salience":0.011608166620135307},{"name":"value","salience":0.00965723767876625}],"question":" In the example Jas showed for the atexit() function printing \"bye!\", I'm confused about where the function call to atexit() actually happened in the main. Does this block imply calling the atexit function or is it just checking if atexit() returns a valid value? Thanks! ","answers":[" atexit() registers a function to be called at termination. In this example there is a function bye() that is being registered. The if statement is executed if atexit() fails. That is, if bye() can't be registered. So the call to atexit() happens when you see it. The call to bye() happens when main returns. ",[" I understand. Thanks! "]]}]}